openapi: 3.1.0
info:
  title: Income Service API
  version: 1.0.0
  description: |
    REST API for managing income records. The specification defines CRUD operations
    for creating, reading, updating, and deleting income items.
  contact:
    name: API Support
    email: support@example.com
servers:
- url: https://api.example.com
  description: Production server
- url: http://localhost:8080
  description: Local development server
tags:
- name: Income
  description: Manage income records.
paths:
  "/incomes":
    get:
      summary: List income
      description: Retrieve a paginated list of income.
      operationId: listIncome
      tags:
      - Income
      parameters:
      - "$ref": "./components/common-parameters.yaml#/SearchQueryParam"
      - "$ref": "./components/common-parameters.yaml#/LimitParam"
      - "$ref": "./components/common-parameters.yaml#/OffsetParam"
      responses:
        '200':
          description: A paginated collection of income.
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/IncomeList"
        '400':
          "$ref": "./components/common-responses.yaml#/BadRequest"
        '500':
          "$ref": "./components/common-responses.yaml#/InternalError"
    post:
      summary: Create income
      description: Create a new income record.
      operationId: createIncome
      tags:
      - Income
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/IncomeCreate"
      responses:
        '201':
          description: Income created successfully.
          headers:
            Location:
              description: URL of the newly created income resource.
              schema:
                type: string
                format: uri
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Income"
        '400':
          "$ref": "./components/common-responses.yaml#/BadRequest"
        '409':
          "$ref": "./components/common-responses.yaml#/Conflict"
        '422':
          "$ref": "./components/common-responses.yaml#/UnprocessableEntity"
        '500':
          "$ref": "./components/common-responses.yaml#/InternalError"
  "/incomes/{incomeId}":
    parameters:
    - name: incomeId
      in: path
      required: true
      description: Unique identifier of the income.
      schema:
        type: string
        format: uuid
    get:
      summary: Get income
      description: Retrieve a single income by identifier.
      operationId: getIncome
      tags:
      - Income
      responses:
        '200':
          description: Income retrieved successfully.
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Income"
        '404':
          "$ref": "./components/common-responses.yaml#/NotFound"
        '500':
          "$ref": "./components/common-responses.yaml#/InternalError"
    patch:
      summary: Update income
      description: |
        Apply partial updates to an existing income. The `type` field cannot
        be changed after creation.
      operationId: updateIncome
      tags:
      - Income
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/IncomeUpdate"
      responses:
        '200':
          description: Income updated successfully.
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Income"
        '400':
          "$ref": "./components/common-responses.yaml#/BadRequest"
        '404':
          "$ref": "./components/common-responses.yaml#/NotFound"
        '409':
          "$ref": "./components/common-responses.yaml#/Conflict"
        '422':
          "$ref": "./components/common-responses.yaml#/UnprocessableEntity"
        '500':
          "$ref": "./components/common-responses.yaml#/InternalError"
    delete:
      summary: Delete income
      description: Permanently remove an income record.
      operationId: deleteIncome
      tags:
      - Income
      responses:
        '204':
          description: Income deleted successfully.
        '404':
          "$ref": "./components/common-responses.yaml#/NotFound"
        '500':
          "$ref": "./components/common-responses.yaml#/InternalError"
components:
  schemas:
    Income:
      "$ref": "./components/income.yaml#/Income"
    IncomeCreate:
      allOf:
      - "$ref": "./components/income.yaml#/Income"
      - type: object
        description: |
          Payload to create a new income record.

          Note: id is server-generated (readOnly) and will be returned in the response.
    IncomeUpdate:
      allOf:
      - "$ref": "./components/income.yaml#/Income"
      - type: object
        description: |
          Payload to update one or more mutable fields of an existing income.
          Partial updates are supported.

          Note: id is server-generated (readOnly) and cannot be updated.
          The `type` field cannot be changed after creation.
        minProperties: 1
    IncomeList:
      type: object
      additionalProperties: false
      required:
      - items
      - total
      - limit
      - offset
      properties:
        items:
          type: array
          items:
            "$ref": "#/components/schemas/Income"
        total:
          type: integer
          minimum: 0
          description: Total number of income available.
        limit:
          type: integer
          minimum: 1
          maximum: 100
          description: Maximum number of income requested.
        offset:
          type: integer
          minimum: 0
          description: Number of items skipped before the current page.

