openapi: 3.1.0
info:
  title: Person Service API
  version: 1.0.0
  description: |
    REST API for managing person records. The specification defines CRUD operations
    for creating, reading, updating, and deleting people.
  contact:
    name: API Support
    email: support@example.com
servers:
- url: https://api.example.com
  description: Production server
- url: http://localhost:8080
  description: Local development server
tags:
- name: Persons
  description: Manage person records.
paths:
  "/persons":
    get:
      summary: List persons
      description: Retrieve a paginated list of persons.
      operationId: listPersons
      tags:
      - Persons
      parameters:
      - "$ref": "./components/common-parameters.yaml#/LimitParam"
      - "$ref": "./components/common-parameters.yaml#/OffsetParam"
      responses:
        '200':
          description: A paginated collection of persons.
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/PersonList"
        '400':
          "$ref": "./components/common-responses.yaml#/BadRequest"
        '500':
          "$ref": "./components/common-responses.yaml#/InternalError"
    post:
      summary: Create a person
      description: Create a new person record.
      operationId: createPerson
      tags:
      - Persons
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/PersonCreate"
      responses:
        '201':
          description: Person created successfully.
          headers:
            Location:
              description: URL of the newly created person resource.
              schema:
                type: string
                format: uri
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Person"
        '400':
          "$ref": "./components/common-responses.yaml#/BadRequest"
        '409':
          "$ref": "#/components/responses/Conflict"
        '422':
          "$ref": "./components/common-responses.yaml#/UnprocessableEntity"
        '500':
          "$ref": "./components/common-responses.yaml#/InternalError"
  "/persons/{personId}":
    parameters:
    - "$ref": "#/components/parameters/PersonIdParam"
    get:
      summary: Get a person
      description: Retrieve a single person by identifier.
      operationId: getPerson
      tags:
      - Persons
      responses:
        '200':
          description: Person retrieved successfully.
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Person"
              examples:
                PersonExample1:
                  "$ref": "./examples/persons.yaml#/PersonExample1"
        '404':
          "$ref": "./components/common-responses.yaml#/NotFound"
        '500':
          "$ref": "./components/common-responses.yaml#/InternalError"
    patch:
      summary: Update a person
      description: Apply partial updates to an existing person.
      operationId: updatePerson
      tags:
      - Persons
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/PersonUpdate"
      responses:
        '200':
          description: Person updated successfully.
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Person"
        '400':
          "$ref": "./components/common-responses.yaml#/BadRequest"
        '404':
          "$ref": "./components/common-responses.yaml#/NotFound"
        '409':
          "$ref": "#/components/responses/Conflict"
        '422':
          "$ref": "./components/common-responses.yaml#/UnprocessableEntity"
        '500':
          "$ref": "./components/common-responses.yaml#/InternalError"
    delete:
      summary: Delete a person
      description: Permanently remove a person record.
      operationId: deletePerson
      tags:
      - Persons
      responses:
        '204':
          description: Person deleted successfully.
        '404':
          "$ref": "./components/common-responses.yaml#/NotFound"
        '500':
          "$ref": "./components/common-responses.yaml#/InternalError"
components:
  parameters:
    PersonIdParam:
      name: personId
      in: path
      required: true
      description: Unique identifier of the person.
      schema:
        type: string
        format: uuid
      example: 4d1f13f0-3e26-4c50-b2fb-8d140f7ec1c2
  schemas:
    Person:
      "$ref": "./components/person.yaml#/Person"
    PersonCreate:
      allOf:
      - "$ref": "./components/person.yaml#/Person"
      - type: object
        description: |
          Payload to create a new person record.
          
          Note: id, createdAt, and updatedAt are server-generated (readOnly) and will be returned in the response.
    PersonUpdate:
      allOf:
      - "$ref": "./components/person.yaml#/Person"
      - type: object
        description: |
          Payload to update one or more mutable fields of an existing person. Partial updates are supported.
          
          Note: id, createdAt, and updatedAt are server-generated (readOnly) and cannot be updated.
        minProperties: 1
    PersonList:
      type: object
      additionalProperties: false
      required:
      - items
      - total
      - limit
      - offset
      properties:
        items:
          type: array
          items:
            "$ref": "#/components/schemas/Person"
        total:
          type: integer
          minimum: 0
          description: Total number of persons available.
        limit:
          type: integer
          minimum: 1
          maximum: 100
          description: Maximum number of persons requested.
        offset:
          type: integer
          minimum: 0
          description: Number of items skipped before the current page.
        hasNext:
          type: boolean
          description: Indicates whether more persons are available beyond the current
            page.
  responses:
    Conflict:
      description: A conflict occurred with the current state of the resource.
      content:
        application/json:
          schema:
            "$ref": "./components/common-responses.yaml#/Error"
